version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    image: im-system-app
    volumes:
      - ./:/var/www
    container_name: IMSystem_backend
    restart: always
    networks:
      - im-network

  nginx:
    image: nginx:latest
    container_name: IMSystem_server
    volumes:
     - ./build/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
     - ./:/var/www
    ports:
     - "8080:80"
    depends_on:
      - mysql
      - app
    networks:
      - im-network

  mysql:
    image: mysql:latest
    container_name: IMSystem_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=IMSystem
      - MYSQL_ROOT_PASSWORD=ArcSecurePassword
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./build/mysql.cnf:/etc/mysql/conf.d/custom.cnf
    networks:
      - im-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: IM_Database_admin
    ports:
    - "9090:80"
    networks:
      - im-network
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql

networks:
  im-network:
    driver: bridge

volumes:
  mysql_data:
  app_data:


